[project]
name = "ocean-simulation"
version = "0.1.0"
description = "Ocean simulation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.isort]
profile = "black"
force_single_line = true
